In [5]:
from collections import Counter
import pickle

import nltk
from nltk.corpus import stopwords
import pandas as pd

In [6]:
with open('data/out/clean_stories.pickle', 'rb') as f:
    stories = pickle.load(f)

In [7]:
len(stories)

98

In [8]:
N = 20

In [9]:
all_words = [w for story in stories for w in story['text'].split()]

In [10]:
len(all_words)

2830608

In [11]:
all_counter = Counter(all_words)

In [12]:
all_counter.most_common(N)

[('ojos', 20383),
 ('dije', 13366),
 ('cabeza', 10363),
 ('mano', 10303),
 ('puerta', 9683),
 ('manos', 9043),
 ('quiero', 8770),
 ('mirada', 8763),
 ('cuerpo', 8184),
 ('casa', 8039),
 ('voz', 7857),
 ('tiempo', 7383),
 ('sangre', 7355),
 ('podia', 7204),
 ('habitacion', 7132),
 ('sonrisa', 6881),
 ('pregunto', 6821),
 ('rostro', 6775),
 ('siento', 6473),
 ('miro', 6182)]

In [13]:
v_words = [w for story in stories for w in story['text'].split() if story['category'] == 'VAMPIROS (HISTORIAS EN ESPANOL)']

In [14]:
len(v_words)

1712788

In [15]:
v_counter = Counter(v_words)

In [16]:
v_counter.most_common(N)

[('ojos', 12339),
 ('dije', 9538),
 ('cabeza', 6300),
 ('mano', 6272),
 ('puerta', 6091),
 ('sangre', 5810),
 ('mirada', 5677),
 ('manos', 5509),
 ('quiero', 5085),
 ('podia', 4944),
 ('cuerpo', 4938),
 ('tiempo', 4858),
 ('voz', 4807),
 ('casa', 4667),
 ('rostro', 4510),
 ('pregunto', 4445),
 ('habitacion', 4351),
 ('sonrisa', 4257),
 ('vampiro', 4112),
 ('queria', 4077)]

In [17]:
ww_words = [w for story in stories for w in story['text'].split() if story['category'] == 'HOMBRES LOBO (HISTORIAS EN ESPAÃ‘OL)']

In [18]:
len(ww_words)

1117820

In [19]:
ww_counter = Counter(ww_words)

In [20]:
ww_counter.most_common(N)

[('ojos', 8044),
 ('cabeza', 4063),
 ('mano', 4031),
 ('dije', 3828),
 ('quiero', 3685),
 ('puerta', 3592),
 ('manos', 3534),
 ('casa', 3372),
 ('cuerpo', 3246),
 ('mirada', 3086),
 ('voz', 3050),
 ('siento', 2803),
 ('habitacion', 2781),
 ('brazos', 2660),
 ('sonrisa', 2624),
 ('tiempo', 2525),
 ('lobo', 2502),
 ('padre', 2464),
 ('labios', 2417),
 ('pregunto', 2376)]

In [21]:
union_top_words = set(w for w, f in v_counter.most_common(N)).union(w for w, f in ww_counter.most_common(N))

In [22]:
top_df = pd.DataFrame(
    data=[[all_counter[w], v_counter[w], ww_counter[w]] for w in sorted(union_top_words)],
    index=sorted(union_top_words),
    columns=['Freq. total', 'Freq. vampires', 'Freq. werewolves']
)

In [23]:
top_df.sort_values('Freq. total', ascending=False)

            Freq. total  Freq. vampires  Freq. werewolves
ojos              20383           12339              8044
dije              13366            9538              3828
cabeza            10363            6300              4063
mano              10303            6272              4031
puerta             9683            6091              3592
manos              9043            5509              3534
quiero             8770            5085              3685
mirada             8763            5677              3086
cuerpo             8184            4938              3246
casa               8039            4667              3372
voz                7857            4807              3050
tiempo             7383            4858              2525
sangre             7355            5810              1545
podia              7204            4944              2260
habitacion         7132            4351              2781
sonrisa            6881            4257              2624
pregunto           6821            4445              2376
rostro             6775            4510              2265
siento             6473            3670              2803
queria             6119            4077              2042
padre              5755            3291              2464
labios             5737            3320              2417
brazos             5716            3056              2660
vampiro            4515            4112               403
lobo               3362             860              2502

In [24]:
top_df.sort_values('Freq. vampires', ascending=False)

            Freq. total  Freq. vampires  Freq. werewolves
ojos              20383           12339              8044
dije              13366            9538              3828
cabeza            10363            6300              4063
mano              10303            6272              4031
puerta             9683            6091              3592
sangre             7355            5810              1545
mirada             8763            5677              3086
manos              9043            5509              3534
quiero             8770            5085              3685
podia              7204            4944              2260
cuerpo             8184            4938              3246
tiempo             7383            4858              2525
voz                7857            4807              3050
casa               8039            4667              3372
rostro             6775            4510              2265
pregunto           6821            4445              2376
habitacion         7132            4351              2781
sonrisa            6881            4257              2624
vampiro            4515            4112               403
queria             6119            4077              2042
siento             6473            3670              2803
labios             5737            3320              2417
padre              5755            3291              2464
brazos             5716            3056              2660
lobo               3362             860              2502

In [25]:
top_df.sort_values('Freq. werewolves', ascending=False)

            Freq. total  Freq. vampires  Freq. werewolves
ojos              20383           12339              8044
cabeza            10363            6300              4063
mano              10303            6272              4031
dije              13366            9538              3828
quiero             8770            5085              3685
puerta             9683            6091              3592
manos              9043            5509              3534
casa               8039            4667              3372
cuerpo             8184            4938              3246
mirada             8763            5677              3086
voz                7857            4807              3050
siento             6473            3670              2803
habitacion         7132            4351              2781
brazos             5716            3056              2660
sonrisa            6881            4257              2624
tiempo             7383            4858              2525
lobo               3362             860              2502
padre              5755            3291              2464
labios             5737            3320              2417
pregunto           6821            4445              2376
rostro             6775            4510              2265
podia              7204            4944              2260
queria             6119            4077              2042
sangre             7355            5810              1545
vampiro            4515            4112               403